#include <stdio.h>
#include <stdlib.h>
#include <httpd.h>

int queralyzer(char * query, char** query_op);

extern "C"
{
/*
** This is a static page of HTML. It is loaded into the content
** tree using httpdAddStaticContent( ).
*/
#define test1_html "<HTML><BODY>This is just a test</BODY>"

/*
** Below are 2 dynamic pages, each generated by a C function. The first
** is a simple page that offers a little dynamic info (the process ID)
** and then sets up a test link and a simple form.
**
** The second page processes the form. As you can see, you can access
** the form data from within your C code by accessing the symbol table
** using httpdGetVariableByName() (and other similar functions). You
** can also include variables in the string passed to httpdOutput( ) and
** they will be expanded automatically.
*/
void dummy_html(httpd *server)
{
	httpdPrintf(server, "Welcome to the httpd queralyzer");
	httpdPrintf(server, "<P><FORM ACTION=query METHOD=POST>\n");
	httpdPrintf(server, "Enter your query <INPUT NAME=query SIZE=4096>\n");
	httpdPrintf(server, "<INPUT TYPE=SUBMIT VALUE=Click!><P></FORM>\n" );
	return;	
}

void query_html(httpd *server)
{
	char*  query_op;
	httpVar *variable;
	/*
	** Grab the symbol table entry to see if the variable exists
	*/
	variable = httpdGetVariableByName(server, "query");
	if (variable == NULL)
	{
		httpdPrintf(server,"Missing form data!");
		return;
	}
	/*
	** Use httpdOutput() rather than httpdPrintf() so that the variable
	** embedded in the text is expanded automatically
	*/
	char *query =variable->value;
	//httpdOutput(server,"The query you have entered is $query");
	//Call the queralyzer function here
	queralyzer(query, &query_op);
	//httpdPrintf(server, "\n%s\n", httpdRequestPath(server));
	//httpdPrintf(server, "%s\n", httpdRequestMethodName(server));
	httpdPrintf(server, "%s\n", query_op);
	//printf("%s\n", query_op);
	return;	
}

int main( int argc, char *argv[])
{
	httpd *server;
	/*
	** Create a server and setup our logging
	*/
	server = httpdCreate(NULL,1234);
	if (server == NULL)
	{
	perror("Can't create server");
	exit(1);
	}
	httpdSetAccessLog(server, stdout);
	httpdSetErrorLog(server, stderr);
	/*
	** Setup some content for the server
	*/
	httpdAddCContent(server,"/", "dummy", HTTP_TRUE, NULL, dummy_html);
	httpdAddCContent(server,"/", "query", HTTP_TRUE, NULL, query_html);
	/*
	** Go into our service loop
	*/
	while(1 == 1)
	{
	if (httpdGetConnection(server, 0) < 0)
		continue;
	if(httpdReadRequest(server) < 0)
	{
		httpdEndRequest(server);
		continue;
	}
	else
 	{
		httpdProcessRequest(server);
		httpdEndRequest(server);
	}
	}
}
}
